### ISSUE TITLE
version of manticore, latest breaks while 3.2.0 works.

### ISSUE THREAD

**Issue by mylinttrap** [Suika/foolstack-docker#5]
Found an issue on rebuilds in my local that can be tied to using :latest for manticore. 
In my experiments I found that the last stable version, for me, was 3.2.0. 
The latest tag from : https://hub.docker.com/r/manticoresearch/manticore/tags is tied to some weird versioning in the last month. The last build in repo (here) was about 3 months back. 
FROM manticoresearch/manticore:latest
should be 
FROM manticoresearch/manticore:3.2.0
in order to avoid sphynx restarting ad nauseam on boot. 
>>>https://github.com/Suika/foolstack-docker/blob/master/manticore/Dockerfile

**Comment by Suika** [comment]
Thanks, will fix in the following days.
